FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        curl \
        mtr \
        telnet \
        dnsutils \
        iputils-ping \
        vim \
        traceroute \
        redis-tools \
        mysql-client \
        postgresql-client \
        && \
    apt-get clean
