FROM ubuntu:21.10

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        curl \
        mtr \
        telnet \
        dnsutils \
        vim \
        && \
    apt-get clean
