FROM alpine:3.17.0

COPY curl.txt curl.txt

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
        curl \
        mtr \
        busybox-extras \
        iputils \
        bind-tools \
        vim \
        redis \
        mysql-client \
        postgresql-client \
        apache2-utils 

    