name: Build and Deploy to Docker Hub

on:
  push:
    tags:
      - "*"

jobs:
  extract-tag:
    name: Print Github Repo tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Github Tag
        id: extract_tag
        run: |-
          echo "##[set-output name=tag;]$( echo ${GITHUB_REF} | sed 's|refs/tags/||g')"
      - name: print tag
        env:
          TAG: ${{ steps.extract_tag.outputs.tag }}
        run: |-
          echo "tag:$TAG"
    outputs:
      tag: ${{  steps.extract_tag.outputs.tag }}

  print-tag:
    name: Print env TAG
    runs-on: ubuntu-latest
    needs:
      - extract-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print
        env:
          TAG: ${{  github.ref_name }}
        run: |-
          echo "tag:$TAG"

  build-deploy-ubuntu:
    name: Build and Deploy the Ubuntu image
    runs-on: ubuntu-latest
    needs:
      - extract-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile.ubuntu
          platforms: linux/amd64,linux/arm64
          attests: type=sbom,generator=docker/scout-sbom-indexer:latest
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:${{  github.ref_name }}
            ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:${{  github.ref_name }}-ubuntu
            ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:ubuntu
            ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:latest

  build-deploy-alpine:
    name: Build and Deploy the Alpine image
    runs-on: ubuntu-latest
    needs:
      - extract-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          attests: type=sbom,generator=docker/scout-sbom-indexer:latest
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:${{  github.ref_name }}-alpine
            ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:alpine
            ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:minimal
